### ISSUE TITLE
High CPU consumption with `.pdf` files

### ISSUE THREAD

**Issue by sakkamade** [multiSnow/mcomix3#144]
**What is the problem**

Any sort of `.pdf` file (which I tried) 
with `Maximum number of concurrent threads` set to `0`
sends all threads of my CPU to 100% of usage, and does not liberate it until I close the application or the file.

With `1`, amount of CPU usage is still constantly above normal: ~50% on single thread, and leaps to other up to 20-30%.

**Extra information**
- My CPU is Intel i3, 4 threads, 2 cores;
- The same files opens with almost no load on CPU in software such as Okular;
- The behaviour observed only with `.pdf` files. 
(Not with `.cbz`, `.7z`, `.rar`.)

**Comment by multiSnow** [comment]
Okular uses poppler library to read and render each page of pdf.
Of course it should have very good performance since only required page will be decoded only in required dpi and rendered directly without any encoding.

While, mcomix uses mutool (command line tools of mupdf) to 'extract' all of the pages of the pdf in their original dpi and save them as png to avoid quality loses. It means that mutool will be called on every page and do both decode and encode. It is making you feel slow and low performance.

**Comment by sakkamade** [comment]
No, I would not say the performance is low. It's not low nor slow.
It's just, the PC becomes too loud... Like, **too** loud.

I was wondering, does the program extracts every single page at once, right when I open the document?
And may this process be slowed down?

**Comment by sakkamade** [comment]
The value of `Maximum number of pages to store in the cache` seem to make no difference.

**Comment by multiSnow** [comment]
Yes, the program extracts every single page at once the pdf (or any other supported archives) opened. It is so designed by the author of comix and mcomix.
The only way to slow down this prorcess is setting the 'Maximum number of concurrent extraction threads' to 1.
'Maximum number of pages to store in the cache' is not related to the archive extracting, but the image decoding.

**Comment by sakkamade** [comment]
It's all clear to me now. Thank you!

Closing it.
